
on:
  push:



jobs:
  empty-group:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_num: [1, 2, 3]
    concurrency: ${{ fromJson('{}') }}
    steps:
      - name: Wait
        run: sleep 20
